server.port=8080
spring.datasource.url=jdbc:mysql://restaurantedb.cxo2uco0evxi.sa-east-1.rds.amazonaws.com:3306/restauraneDBsql
spring.datasource.username=root
spring.datasource.password=root1234
spring.jpa.hibernate.ddl-auto=update